// <auto-generated />
using System;
using BasicCRUD_With_NET5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicCRUD_With_NET5.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    partial class BooksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("LenderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LenderId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Author", b =>
                {
                    b.HasBaseType("BasicCRUD_With_NET5.Models.Person");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Lender", b =>
                {
                    b.HasBaseType("BasicCRUD_With_NET5.Models.Person");

                    b.HasDiscriminator().HasValue("Lender");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Book", b =>
                {
                    b.HasOne("BasicCRUD_With_NET5.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasicCRUD_With_NET5.Models.Lender", "Lender")
                        .WithMany("Books")
                        .HasForeignKey("LenderId");

                    b.Navigation("Author");

                    b.Navigation("Lender");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BasicCRUD_With_NET5.Models.Lender", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
